### ISSUE TITLE
Unable to select window

### ISSUE THREAD

**Issue by SSriracha** [iVerb1/SourceLiveTimer#1]
So I was using the timer like normal when I wanted to move it. Proceeded to move it and ended up double clicking instead (like a Select All), and now the timer launches but I can't click on it or see it or do anything with it. Help?

**Comment by iVerb1** [comment]
It is likely that the window has gone off screen. The screen location that is restored upon launch is stored in Users/[USER]/AppData/Local/SourceLiveTimer. Try clearing that folder.
